<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <PackageId>InnoClinic.Contracts</PackageId>
    <Version>1.0.4</Version> <Authors>NeedX</Authors>
    <Company>InnoClinic</Company>
    <Description>Shared contracts and events for InnoClinic microservices</Description>
    <RepositoryUrl>https://github.com/XNeedX/InnoClinic.Contracts</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <None Include=".github\workflows\publish-nuget.yml" />
  </ItemGroup>

</Project>
